paths:
  dataset_dir: "/home/lecomte/AstroSpikes/SPADES"
  output_dir: "./generated_dataset/lnes"

transformation:
  method: "lnes"

filter:
  method: "get_distribution"
  parameters:
    conditions:
      - [280, false]
      - [1000, true]
      - [1280, false]

dataset_type: "synthetic"

batch_size: 128
shuffle_count: 1024

alpha: 0.7
input_shape: [240, 240, 3]

learning_rate: 1e-3
metrics:  #don't change this
  - "accuracy"  
epochs: 50
verbose: 2