paths:
  dataset_dir: "/home/lecomte/AstroSpikes/SPADES"
  output_dir: "./generated_dataset"

transformation:
  method: "two_polarity_time_surface"

filter:
  method: "get_distribution"
  parameters:
    conditions:
      - [280, false]
      - [1000, true]
      - [1280, false]

dataset_type: "synthetic"

batch_size: 128
test_split: 0.2

alpha: 0.7
input_shape: [224, 224, 3]

learning_rate: 1e-3
metrics:  #don't change this
  - "mean_absolute_error"  
epochs: 1
verbose: 2