id: mobilenet_lnes_syn
root:
  dataset: "/mnt/isilon/space_cluster/SPADES"
  data_out: "/mnt/isilon/space_cluster/SPADES/synthetic"
  checkpoint: "/home/arathinam/experiments/SPADES/${id}"
  test_data: "/mnt/isilon/space_cluster/SPADES/synthetic/val.csv"

filter:
  method: "get_distribution"
  parameters:
    conditions:
      - [ 280, False ]
      - [ 1000, True ]
      - [ 1280, False ]

data:
  transformation: "lnes"
  source: "synthetic"
  input_size: [640, 360, 3]
  test_split: 0.2

training:
  lr: 1e-4
  num_epochs: 100
  beta_epochs: 5
  verbose: 0
  batch_size: 24
  log_Step: 1
  val_log_Step: 1

model:
  pretrained: False
  trained_weights:

wandb:
  status: 'online'
  exp_id: 'ak_mobnet_lnes_train_alpha_n_loss'