id: fortiss_mobilenet_two_d_histogram_syn
root:
  labels: '/home/lecomte/AstroSpikes/SPADES/spades_label'
  dataset: "/home/lecomte/AstroSpikes/SPADES/synthetic"
  data_out: "/home/lecomte/AstroSpikes/SPADES/synthetic"
  checkpoint: "/home/lecomte/experiments/SPADES/${id}"
  test_data: "/home/lecomte/datasets/SPADES/synthetic/val.csv"
  labels_dir: "/Users/jost/Jost/Code/2024-nc-hackathon-spades/spades_label"

filter:
  method: "get_distribution"
  parameters:
    conditions:
      - [ 280, False ]
      - [ 1000, True ]
      - [ 1280, False ]

data:
  transformation: "lnes"
  source: "synthetic"
  input_size: [1280, 720, 3]
  test_split: 0.2

training:
  lr: 1e-4
  num_epochs: 300
  beta_epochs: 5
  verbose: 0
  batch_size: 16
  log_Step: 1
  val_log_Step: 1

model:
  heatmap: False
  pretrained: False
  trained_weights: /home/arunkumar/experiments/SPADES/mobilenet_lnes_syn/model_280_0.0921.keras

wandb:
  project_id: mobilenet-astrospikes
  status: 'offline'
  exp_id: 'fortiss_test_640*360'