id: fortiss_mobilenet_two_d_histogram_syn
root:
  labels: '/home/arunkumar/datasets/SPADES/synthetic'
  data_out: "/home/arunkumar/datasets/SPADES/synthetic"
  checkpoint: "/home/arunkumar/dev-python/2024-nc-hackathon-AstroSpikes/outputs/${id}"
  test_data: "/home/arunkumar/datasets/SPADES/synthetic/val.csv"
  labels_dir: "/home/arunkumar/datasets/SPADES/synthetic"

dataset:
  root_dir: "/home/arunkumar/datasets/SPADES/synthetic"
  train_data_path: ${dataset.root_dir}/lnes_cropped/train/keypoints.csv
  val_data_path: ${dataset.root_dir}/lnes_cropped/train/keypoints.csv

filter:
  method: "get_distribution"
  parameters:
    conditions:
      - [ 280, False ]
      - [ 1000, True ]
      - [ 1280, False ]

data:
  transformation: "lnes"
  source: "synthetic"
  input_size: [1280, 720, 3]
  test_split: 0.2

training:
  input_size: [224, 224, 3]
  lr: 1e-4
  num_epochs: 300
  beta_epochs: 5
  verbose: 0
  batch_size: 16
  log_Step: 1
  val_log_Step: 1
  distributed: True

model:
  heatmap: True
  pretrained: False
  trained_weights:

wandb:
  project_id: mobilenet-astrospikes
  status: 'online'
  exp_id: 'heatmap_dsnt'